### ISSUE TITLE
A suggested enhancement

### ISSUE THREAD

**Issue by CharlesGodwin** [thevoltagesource/myicomfort#1]
Thanks for this code. It does all that I need from the service. But.. I am logging my thermostat data and needed a JSON string. I implemented this by extending your class as follows. But could you just add this method to your base class for others to share. I use `OrderedDict `so the JSON string is always in the same order. The base Python dictionary does not guarantee order.
<pre>
from collections import OrderedDict
class TstatJson(Tstat):
    def getJSON(self, indent=None):
        data = OrderedDict()
        self.pull_status()
        data["serial_number"] = self._serial_number
        data["state"] = self.state
        data["state_text"] = self.state_list[self.state]
        data["op_mode"] = self.op_mode
        data["op_mode_text"] = self.op_mode_list[self.op_mode]
        data["fan_mode"] = self.fan_mode
        data["fan_mode_text"] = self.fan_mode_list[self._fan_mode]
        data["away_mode"] = self.away_mode
        data["temperature_units"] = self.temperature_units
        data["temperature_units_text"] = self.temp_units_list[self.temperature_units]
        data["current_temperature"] = self.current_temperature
        data["current_humidity"] = self.current_humidity
        points = self.set_points
        data["heat_to"] = points[0]
        data["cool_to"] = points[1]
        return json.dumps(data, indent=indent)
</pre>

Thanks

**Comment by thevoltagesource** [comment]
I apologize for the delay in responding, I must have missed the notification.  I have a bug to fix in the code so as soon as I have a chance to jump back into coding mode, I will knock this out as well.

**Comment by thevoltagesource** [comment]
Finally added get_json().  Check out version 0.4.0 and see if it works as expected.  I will bump the version in the home assistant integration if if looks good to you.

**Comment by CharlesGodwin** [comment]
I reviewed the change and it looks right except for a minor detail.

I had suggested using OrderedDict so that the order of every element in the Json string would be guaranteed to always be in the same order. Until a recent release of Python 3.x, the order of elements in a dictionary was not defined unless using OrderedDict. This is a question of style, not code correctness, so the choice is yours.

If you choose to use OrderedDict, change line 278 to `data = OrderedDict()`
If you choose to not use OrderedDict, then delete line 43 as it's not needed

Thank you for this package, I find it useful.

**Comment by thevoltagesource** [comment]
That was unintentional.  I was playing with the difference between the two types across different versions of Python and I apparently forgot to revert before committing my work.  Check out 0.4.1 and let me know if I got everything right this time.  I'm glad you are putting this to good use.  It is nice to know my efforts are benefiting others as well.

**Comment by CharlesGodwin** [comment]
Looks good.
Thanks
